from . import hospital_doctor
from . import hospital_nurse
from . import hospital_patient
from . import medical_consultation_consultation
from . import medical_consultation_diagnosis_advice
from . import medical_consultation_diagnosis_detail
from . import medical_consultation_diagnosis
from . import medical_consultation_request_symptom_rel
from . import medical_consultation_request