from . import hospital_disease_symptom_rel
from . import hospital_disease_type
from . import hospital_disease
from . import hospital_doctor
from . import hospital_efficiency_level
from . import product_template
from . import hospital_nurse
from . import hospital_patient
from . import hospital_severity_level
from . import hospital_symptom_product_rel
from . import hospital_symptom
from . import res_currency
from . import res_partner
from . import res_users